--칼럼 추가
ALTER TABLE MEMBER ADD MEMBER_POSTCODE NUMBER;
ALTER TABLE DORMANT_MEMBER ADD MEMBER_POSTCODE NUMBER;
ALTER TABLE SIGN_OUT_MEMBER ADD MEMBER_POSTCODE NUMBER;

ALTER TABLE MEMBER ADD MEMBER_ROAD_ADDRESS VARCHAR2(100 BYTE);
ALTER TABLE DORMANT_MEMBER ADD MEMBER_ROAD_ADDRESS VARCHAR2(100 BYTE);
ALTER TABLE SIGN_OUT_MEMBER ADD MEMBER_ROAD_ADDRESS VARCHAR2(100 BYTE);

ALTER TABLE MEMBER ADD MEMBER_DETAIL_ADDRESS VARCHAR2(100 BYTE);
ALTER TABLE DORMANT_MEMBER ADD MEMBER_DETAIL_ADDRESS VARCHAR2(100 BYTE);
ALTER TABLE SIGN_OUT_MEMBER ADD MEMBER_DETAIL_ADDRESS VARCHAR2(100 BYTE);


--칼럼 수정
ALTER TABLE MEMBER RENAME COLUMN MEMBER_SIGN_IN TO MEMBER_SIGN_UP;
ALTER TABLE DORMANT_MEMBER RENAME COLUMN MEMBER_SIGN_IN TO MEMBER_SIGN_UP;
ALTER TABLE SIGN_OUT_MEMBER RENAME COLUMN MEMBER_SIGN_IN TO MEMBER_SIGN_UP;
ALTER TABLE MEMBER_LOG RENAME COLUMN MEMBER_LOG_SIGN_UP TO MEMBER_LOG_SIGN_IN;


-- 칼럼 삭제
ALTER TABLE MEMBER DROP COLUMN MEMBER_ADDRESS;
ALTER TABLE DORMANT_MEMBER DROP COLUMN MEMBER_ADDRESS;
ALTER TABLE SIGN_OUT_MEMBER DROP COLUMN MEMBER_ADDRESS;


--트리거
CREATE OR REPLACE TRIGGER SIGN_OUT_TRIGGER
    AFTER DELETE
    ON MEMBER
    FOR EACH ROW
BEGIN
    INSERT INTO SIGN_OUT_MEMBER
        (SIGN_OUT_NO, MEMBER_NO, MEMBER_ID, MEMBER_NAME, MEMBER_PHONE, MEMBER_EMAIL, MEMBER_POSTCODE, MEMBER_ROAD_ADDRESS, MEMBER_DETAIL_ADDRESS, MEMBER_AGREE_STATE, MEMBER_SIGN_UP)
    VALUES
        (SIGN_OUT_MEMBER_SEQ.NEXTVAL, :OLD.MEMBER_NO, :OLD.MEMBER_ID, :OLD.MEMBER_NAME, :OLD.MEMBER_PHONE, :OLD.MEMBER_EMAIL, :OLD.MEMBER_POSTCODE, :OLD.MEMBER_ROAD_ADDRESS, :OLD.MEMBER_DETAIL_ADDRESS, :OLD.MEMBER_AGREE_STATE, :OLD.MEMBER_SIGN_UP);
END SIGN_OUT_TRIGGER;
